drop DATABASE IF EXISTS escola;
CREATE SCHEMA IF NOT EXISTS escola DEFAULT CHARACTER SET utf8 ;
USE escola;


SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------
-- Table PESSOA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PESSOA (
  ID_PESSOA INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  CPF VARCHAR(45) NOT NULL,
  DT_NASC DATE NOT NULL,
  TIPO_PESSOA TINYINT(2) NOT NULL,
  ATIVO TINYINT(2) NOT NULL,
  PRIMARY KEY (ID_PESSOA))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ALUNO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ALUNO (
  ID_ALUNO INT NOT NULL AUTO_INCREMENT,
  ID_PESSOA INT NOT NULL,
  PRIMARY KEY (ID_ALUNO),
    CONSTRAINT fk_ALUNO_PESSOA1  FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA (ID_PESSOA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PROFESSOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PROFESSOR (
  ID_PROFESSOR INT NOT NULL AUTO_INCREMENT,
  ID_PESSOA INT NOT NULL,
  PRIMARY KEY (ID_PROFESSOR),
  CONSTRAINT fk_PROFESSOR_PESSOA1
    FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA (ID_PESSOA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table TURMA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TURMA (
  ID_TURMA INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(45) NOT NULL,
  DT_INI DATE NOT NULL,
  DT_FIM DATE NOT NULL,
  SEMESTRE INT NOT NULL,
  ATIVO TINYINT(2) NOT NULL,
  PRIMARY KEY (ID_TURMA))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CURSO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CURSO (
  ID_CURSO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  ATIVO TINYINT(2) NOT NULL,
  PRIMARY KEY (ID_CURSO))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ALUNO_TURMA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ALUNO_TURMA (
  ID_ALUNO_TURMA INT NOT NULL AUTO_INCREMENT,
  ID_ALUNO INT NOT NULL,
  ID_TURMA INT NOT NULL,
  ID_CURSO INT NOT NULL,
  PRIMARY KEY (ID_ALUNO_TURMA),
  CONSTRAINT fk_ALUNO_has_TURMA_ALUNO
    FOREIGN KEY (ID_ALUNO)
    REFERENCES ALUNO (ID_ALUNO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ALUNO_has_TURMA_TURMA1
    FOREIGN KEY (ID_TURMA)
    REFERENCES TURMA (ID_TURMA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ALUNO_TURMA_CURSO1
    FOREIGN KEY (ID_CURSO)
    REFERENCES CURSO (ID_CURSO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PERIODO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PERIODO (
  ID_PERIODO INT NOT NULL AUTO_INCREMENT,
  PERIODO VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_PERIODO))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MATERIA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MATERIA (
  ID_MATERIA INT NOT NULL AUTO_INCREMENT,
  ID_PERIODO INT NOT NULL,
  ID_PROFESSOR INT NOT NULL,
  NOME VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_MATERIA),
  CONSTRAINT fk_MATERIA_PERIODO1
    FOREIGN KEY (ID_PERIODO)
    REFERENCES PERIODO (ID_PERIODO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_MATERIA_PROFESSOR1
    FOREIGN KEY (ID_PROFESSOR)
    REFERENCES PROFESSOR (ID_PROFESSOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ALUNO_TURMA_MATERIA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ALUNO_TURMA_MATERIA (
  ID_TURMA_MATERIA INT NOT NULL AUTO_INCREMENT,
  ID_ALUNO_TURMA INT NOT NULL,
  ID_MATERIA INT NOT NULL,
  PRIMARY KEY (ID_TURMA_MATERIA),
  CONSTRAINT fk_ALUNO_TURMA_has_MATERIA_ALUNO_TURMA1
    FOREIGN KEY (ID_ALUNO_TURMA)
    REFERENCES ALUNO_TURMA (ID_ALUNO_TURMA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ALUNO_TURMA_has_MATERIA_MATERIA1
    FOREIGN KEY (ID_MATERIA)
    REFERENCES MATERIA (ID_MATERIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table DIARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIARIO (
  ID_DIARIO INT NOT NULL AUTO_INCREMENT,
  ID_TURMA_MATERIA INT NOT NULL,
  ID_PROFESSOR INT NOT NULL,
  DATA DATE NOT NULL,
  QTDE_AULAS_DIA INT(11) NOT NULL,
  QTDE_FALTAS INT(11) NOT NULL,
  PRIMARY KEY (ID_DIARIO),
  CONSTRAINT fk_ALUNO_TURMA_has_MATERIA_has_PROFESSOR_ALUNO_TURMA_has_MATE1
    FOREIGN KEY (ID_TURMA_MATERIA)
    REFERENCES ALUNO_TURMA_MATERIA (ID_TURMA_MATERIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ALUNO_TURMA_has_MATERIA_has_PROFESSOR_PROFESSOR1
    FOREIGN KEY (ID_PROFESSOR)
    REFERENCES PROFESSOR (ID_PROFESSOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CURSO_MATERIA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CURSO_MATERIA (
  ID_CURSO_MATERIA INT NOT NULL AUTO_INCREMENT,
  ID_CURSO INT NOT NULL,
  ID_MATERIA INT NOT NULL,
  PRIMARY KEY (ID_CURSO_MATERIA),
  CONSTRAINT fk_CURSO_has_MATERIA_CURSO1
    FOREIGN KEY (ID_CURSO)
    REFERENCES CURSO (ID_CURSO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CURSO_has_MATERIA_MATERIA1
    FOREIGN KEY (ID_MATERIA)
    REFERENCES MATERIA (ID_MATERIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CONTATO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CONTATO (
  ID_CONTATO INT NOT NULL AUTO_INCREMENT,
  ID_PESSOA INT NOT NULL,
  EMAIL VARCHAR(45) NULL,
  TELEFONE VARCHAR(45) NULL,
  CELULAR VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_CONTATO),
  CONSTRAINT fk_CONTATO_PESSOA1
    FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA (ID_PESSOA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table FOTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FOTO (
  ID_FOTO INT NOT NULL AUTO_INCREMENT,
  ID_PESSOA INT NOT NULL,
  FOTO BLOB NOT NULL,
  PRIMARY KEY (ID_FOTO),
  CONSTRAINT fk_FOTO_PESSOA1
    FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA (ID_PESSOA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS = 1;


select NETWORKDAYS('2020-02-10', '2020-05-21');


ALTER TABLE `aluno` AUTO_INCREMENT=1;
ALTER TABLE `aluno_turma` AUTO_INCREMENT=1;
ALTER TABLE `aluno_turma_materia` AUTO_INCREMENT=1;
ALTER TABLE `contato` AUTO_INCREMENT=1;
ALTER TABLE `curso` AUTO_INCREMENT=1;
ALTER TABLE `curso_materia` AUTO_INCREMENT=1;
ALTER TABLE `diario` AUTO_INCREMENT=1;
ALTER TABLE `foto` AUTO_INCREMENT=1;
ALTER TABLE `materia` AUTO_INCREMENT=1;
ALTER TABLE `periodo` AUTO_INCREMENT=1;
ALTER TABLE `pessoa` AUTO_INCREMENT=1;
ALTER TABLE `professor` AUTO_INCREMENT=1;
ALTER TABLE `turma` AUTO_INCREMENT=1;